### ISSUE TITLE
Micro USB bei der GPN Version zu nahe am USB-C Port

### ISSUE THREAD

**Issue by dasrecht** [PirminHndlg/USB-Tester-Anleitung#1]
Hi P0k :wave: 

Danke für das zusammenstellen des Kits an der GPN :) Funktioniert einwandfrei

Einzig gemerkt habe ich das der Micro-USB sehr nahe am USB-C ist. Evtl war da ein bisschen ungenau gearbeitet worden bei der PCB Fabrikation. Dachte ich melde das noch; eventuell weisst du das aber schon.

Gruss /dasrecht

p.s. danke für die Ersatzteile (hab einige gebraucht :joy: )

**Comment by PirminHndlg** [comment]
Das freut mich zu hören, dass alles funktioniert! 

Genau das mit der Micro-USB-Buchse war ein kleiner Fehler von mir. Die habe ich falsch hingesetzt (in den aktuellen gbr-Files ist es richtig). Aber irgendwie klappt es die dazuzuquetschen.

**Comment by dasrecht** [comment]
Hah okay :D dachte schon ich hätte irgendwo was schief angelötet :) Funktioniert alles wie geplant :D
